### ISSUE TITLE
Help with modelbuilder

### ISSUE THREAD

**Issue by m-noor** [ahgroup/modelbuilder#14]
Hi, I find the concept for this tool really interesting. However, I am struggling to get it working.

I am trying to build the model as a system of ODE as attached. Can you suggest how I should go about declaring the parameters and variables?

![modelbuilder equations](https://user-images.githubusercontent.com/36330156/55577951-acb0c200-570c-11e9-9a95-206d7b0e1b86.png)

Thank you

**Comment by andreashandel** [comment]
Right now, the package doesn't allow equations that are not differential equations, that means the mu=..., mu_d=... and m_gln=... equations can't be implemented directly. (Allowing such equations is a feature worth considering in the future, but is likely not going to happen very soon). 

You could still implement the differential equations, it would just be tedious because each time you see a mu or mu_d or m_gln in your differential equations (equations 1,4,5,6,8,9),  you would need to write the full expression of the RHS of equations 2, 3, 7. Once you have re-written your model such that there are only ODE's, you can implement it. It should be possible, but it likely is tedious since you will have lots of terms for each equation.
